name: Build and Push Docker Images

on:
  push:
    paths:
      - 'app1/**'
      - 'app2/**'
      - 'app3/**'
      - 'app4/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [app1, app2, app3, app4]  

    steps:
       
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Check for changes
        id: changes
        run: |
          git fetch 
          if git diff --name-only HEAD~1 HEAD | grep -q "${{ matrix.dir }}"; then
            echo "run_build=true" >> $GITHUB_ENV
          else
            echo "run_build=false" >> $GITHUB_ENV
          fi


      - name: Skip if no changes
        if: env.run_build == 'false'
        run: echo "No changes in ${{ matrix.dir }}. Skipping build."


      - name: Log into Docker Hub
        if: env.run_build == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NAME }}
          password: ${{ secrets.MUSTAFADINCER }}

      - name: Build Docker Image
        if: env.run_build == 'true'
        run: |
          docker build -t ${{ secrets.NAME }}/${{ matrix.dir }}:latest ${{ matrix.dir }}


      - name: Push Docker Image
        if: env.run_build == 'true'
        run: |
          docker push ${{ secrets.NAME }}/${{ matrix.dir }}:latest


#needs , 