name: Build and Push Docker Images

on:
  push:
    paths:
      - 'app1/**'
      - 'app2/**'
      - 'app3/**'
      - 'app4/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [app1, app2, app3, app4] # Her dizin için bir iş çalıştırılacak

    steps:
      # Kodları git üzerinden al ve değişiklikleri kontrol et
      - name: Checkout code
        uses: actions/checkout@v2

      # Değişiklik kontrolü
      - name: Check for changes
        id: changes
        run: |
          git fetch # En güncel durumu almak için fetch komutunu ekledik
          if git diff --name-only HEAD~1 HEAD | grep -q "${{ matrix.dir }}"; then
            echo "run_build=true" >> $GITHUB_ENV
          else
            echo "run_build=false" >> $GITHUB_ENV
          fi

      # Değişiklik yoksa işi atla
      - name: Skip if no changes
        if: env.run_build == 'false'
        run: echo "No changes in ${{ matrix.dir }}. Skipping build."

      # Docker imajını build et
      - name: Log into Docker Hub
        if: env.run_build == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        if: env.run_build == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.dir }}:latest ${{ matrix.dir }}

      # Docker Hub'a push yap
      - name: Push Docker Image
        if: env.run_build == 'true'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.dir }}:latest
